spring:
    datasource:
        url: jdbc:mariadb://arturober.com:3306/productos
        username: example
        password: example
        driver-class-name: org.mariadb.jdbc.Driver

logging.level.org.springframework.jdbc.core: TRACE
